// Field definitions for each category
import { FormField } from './categorySchemas';

export const driverFields: FormField[] = [
  // Basic Information
  {
    name: 'driverName',
    label: 'Driver Name',
    labelFr: 'Nom du chauffeur',
    type: 'text',
    required: true,
    placeholder: 'e.g., John Smith',
    placeholderFr: 'ex. Jean Dupont',
    section: 'Basic Information',
    sectionFr: 'Informations de base',
  },
  {
    name: 'employeeId',
    label: 'Employee ID',
    labelFr: 'ID employé',
    type: 'text',
    placeholder: 'e.g., EMP-001',
    placeholderFr: 'ex. EMP-001',
    section: 'Basic Information',
    sectionFr: 'Informations de base',
  },
  {
    name: 'status',
    label: 'Status',
    labelFr: 'Statut',
    type: 'select',
    options: [
      { value: 'active', label: 'Active', labelFr: 'Actif' },
      { value: 'on_leave', label: 'On Leave', labelFr: 'En congé' },
      { value: 'inactive', label: 'Inactive', labelFr: 'Inactif' },
    ],
    section: 'Basic Information',
    sectionFr: 'Informations de base',
  },
  // Contact Information
  {
    name: 'phone',
    label: 'Phone Number',
    labelFr: 'Téléphone',
    type: 'tel',
    placeholder: 'e.g., 514-555-0123',
    placeholderFr: 'ex. 514-555-0123',
    section: 'Contact Information',
    sectionFr: 'Coordonnées',
  },
  {
    name: 'email',
    label: 'Email',
    labelFr: 'Courriel',
    type: 'email',
    placeholder: 'e.g., john@company.com',
    placeholderFr: 'ex. jean@entreprise.com',
    section: 'Contact Information',
    sectionFr: 'Coordonnées',
  },
  // License & Certifications
  {
    name: 'licenseNumber',
    label: 'License Number',
    labelFr: 'Numéro de permis',
    type: 'text',
    placeholder: 'e.g., D1234-56789-01234',
    section: 'License & Certifications',
    sectionFr: 'Permis et certifications',
  },
  {
    name: 'licenseExpiry',
    label: 'License Expiry Date',
    labelFr: 'Date d\'expiration du permis',
    type: 'date',
    section: 'License & Certifications',
    sectionFr: 'Permis et certifications',
  },
  {
    name: 'certifications',
    label: 'Certifications',
    labelFr: 'Certifications',
    type: 'multiselect',
    options: [
      { value: 'class_1', label: 'Class 1', labelFr: 'Classe 1' },
      { value: 'class_3', label: 'Class 3', labelFr: 'Classe 3' },
      { value: 'dz', label: 'DZ License', labelFr: 'Permis DZ' },
      { value: 'hazmat', label: 'Hazmat', labelFr: 'Matières dangereuses' },
      { value: 'tanker', label: 'Tanker', labelFr: 'Citerne' },
      { value: 'air_brakes', label: 'Air Brakes', labelFr: 'Freins à air' },
    ],
    section: 'License & Certifications',
    sectionFr: 'Permis et certifications',
  },
  // Notes
  {
    name: 'notes',
    label: 'Notes',
    labelFr: 'Notes',
    type: 'textarea',
    placeholder: 'Additional notes...',
    placeholderFr: 'Notes additionnelles...',
    section: 'Additional Notes',
    sectionFr: 'Notes additionnelles',
  },
];

export const vehicleFields: FormField[] = [
  // Vehicle Information
  {
    name: 'vehicleId',
    label: 'Vehicle ID / Fleet Number',
    labelFr: 'ID véhicule / Numéro de flotte',
    type: 'text',
    required: true,
    placeholder: 'e.g., TRUCK-001',
    placeholderFr: 'ex. CAMION-001',
    section: 'Vehicle Information',
    sectionFr: 'Informations véhicule',
  },
  {
    name: 'make',
    label: 'Make',
    labelFr: 'Marque',
    type: 'text',
    placeholder: 'e.g., BYD, Volvo, Tesla',
    placeholderFr: 'ex. BYD, Volvo, Tesla',
    section: 'Vehicle Information',
    sectionFr: 'Informations véhicule',
  },
  {
    name: 'model',
    label: 'Model',
    labelFr: 'Modèle',
    type: 'text',
    placeholder: 'e.g., 8TT, VNR Electric',
    placeholderFr: 'ex. 8TT, VNR Electric',
    section: 'Vehicle Information',
    sectionFr: 'Informations véhicule',
  },
  {
    name: 'year',
    label: 'Year',
    labelFr: 'Année',
    type: 'number',
    placeholder: 'e.g., 2025',
    placeholderFr: 'ex. 2025',
    min: 1990,
    max: 2030,
    section: 'Vehicle Information',
    sectionFr: 'Informations véhicule',
  },
  {
    name: 'vehicleType',
    label: 'Vehicle Type',
    labelFr: 'Type de véhicule',
    type: 'select',
    options: [
      { value: 'electric_truck', label: 'Electric Truck', labelFr: 'Camion électrique' },
      { value: 'diesel_truck', label: 'Diesel Truck', labelFr: 'Camion diesel' },
      { value: 'h2_truck', label: 'Hydrogen Truck', labelFr: 'Camion hydrogène' },
      { value: 'electric_bus', label: 'Electric Bus', labelFr: 'Autobus électrique' },
      { value: 'diesel_bus', label: 'Diesel Bus', labelFr: 'Autobus diesel' },
      { value: 'h2_bus', label: 'Hydrogen Bus', labelFr: 'Autobus hydrogène' },
      { value: 'electric_van', label: 'Electric Van', labelFr: 'Fourgonnette électrique' },
      { value: 'diesel_van', label: 'Diesel Van', labelFr: 'Fourgonnette diesel' },
    ],
    section: 'Vehicle Information',
    sectionFr: 'Informations véhicule',
  },
  {
    name: 'status',
    label: 'Status',
    labelFr: 'Statut',
    type: 'select',
    options: [
      { value: 'active', label: 'Active', labelFr: 'Actif' },
      { value: 'maintenance', label: 'In Maintenance', labelFr: 'En maintenance' },
      { value: 'retired', label: 'Retired', labelFr: 'Retiré' },
    ],
    section: 'Vehicle Information',
    sectionFr: 'Informations véhicule',
  },
  // Power & Performance
  {
    name: 'batteryCapacity',
    label: 'Battery Capacity',
    labelFr: 'Capacité batterie',
    type: 'number',
    placeholder: 'e.g., 400',
    unit: 'kWh',
    section: 'Power & Performance',
    sectionFr: 'Puissance et performance',
    conditionalOn: { field: 'vehicleType', values: ['electric_truck', 'electric_bus', 'electric_van'] },
    helpText: 'Only for electric vehicles',
    helpTextFr: 'Uniquement pour véhicules électriques',
  },
  {
    name: 'hydrogenTankSize',
    label: 'Hydrogen Tank Size',
    labelFr: 'Capacité réservoir H2',
    type: 'number',
    placeholder: 'e.g., 32',
    unit: 'kg',
    section: 'Power & Performance',
    sectionFr: 'Puissance et performance',
    conditionalOn: { field: 'vehicleType', values: ['h2_truck', 'h2_bus'] },
    helpText: 'Only for hydrogen vehicles',
    helpTextFr: 'Uniquement pour véhicules hydrogène',
  },
  {
    name: 'fuelTankSize',
    label: 'Fuel Tank Size',
    labelFr: 'Capacité réservoir',
    type: 'number',
    placeholder: 'e.g., 400',
    unit: 'L',
    section: 'Power & Performance',
    sectionFr: 'Puissance et performance',
    conditionalOn: { field: 'vehicleType', values: ['diesel_truck', 'diesel_bus', 'diesel_van'] },
    helpText: 'Only for diesel vehicles',
    helpTextFr: 'Uniquement pour véhicules diesel',
  },
  {
    name: 'range',
    label: 'Range',
    labelFr: 'Autonomie',
    type: 'number',
    placeholder: 'e.g., 350',
    unit: 'km',
    section: 'Power & Performance',
    sectionFr: 'Puissance et performance',
  },
  {
    name: 'payloadCapacity',
    label: 'Payload Capacity',
    labelFr: 'Capacité de charge',
    type: 'number',
    placeholder: 'e.g., 18000',
    unit: 'kg',
    section: 'Power & Performance',
    sectionFr: 'Puissance et performance',
  },
  // Registration
  {
    name: 'vin',
    label: 'VIN',
    labelFr: 'NIV',
    type: 'text',
    placeholder: 'e.g., 1HGBH41JXMN109186',
    section: 'Registration',
    sectionFr: 'Immatriculation',
  },
  {
    name: 'licensePlate',
    label: 'License Plate',
    labelFr: 'Plaque d\'immatriculation',
    type: 'text',
    placeholder: 'e.g., ABC 123',
    section: 'Registration',
    sectionFr: 'Immatriculation',
  },
  {
    name: 'currentMileage',
    label: 'Current Mileage',
    labelFr: 'Kilométrage actuel',
    type: 'number',
    placeholder: 'e.g., 50000',
    unit: 'km',
    section: 'Registration',
    sectionFr: 'Immatriculation',
  },
  // Purchase Information
  {
    name: 'purchaseDate',
    label: 'Purchase Date',
    labelFr: 'Date d\'achat',
    type: 'date',
    section: 'Purchase Information',
    sectionFr: 'Informations d\'achat',
  },
  {
    name: 'purchasePrice',
    label: 'Purchase Price',
    labelFr: 'Prix d\'achat',
    type: 'number',
    placeholder: 'e.g., 150000',
    unit: 'CAD',
    section: 'Purchase Information',
    sectionFr: 'Informations d\'achat',
  },
  // Notes
  {
    name: 'notes',
    label: 'Notes',
    labelFr: 'Notes',
    type: 'textarea',
    placeholder: 'Additional notes...',
    placeholderFr: 'Notes additionnelles...',
    section: 'Additional Notes',
    sectionFr: 'Notes additionnelles',
  },
];

export const maintenanceFields: FormField[] = [
  // Equipment Info
  {
    name: 'equipmentId',
    label: 'Vehicle/Equipment ID',
    labelFr: 'ID véhicule/équipement',
    type: 'text',
    required: true,
    placeholder: 'e.g., TRUCK-001',
    placeholderFr: 'ex. CAMION-001',
    section: 'Equipment Info',
    sectionFr: 'Informations équipement',
  },
  {
    name: 'maintenanceType',
    label: 'Maintenance Type',
    labelFr: 'Type de maintenance',
    type: 'select',
    options: [
      { value: 'oil_change', label: 'Oil Change', labelFr: 'Changement d\'huile' },
      { value: 'tire_rotation', label: 'Tire Rotation', labelFr: 'Rotation des pneus' },
      { value: 'battery_check', label: 'Battery Check', labelFr: 'Vérification batterie' },
      { value: 'inspection', label: 'Inspection', labelFr: 'Inspection' },
      { value: 'brake_service', label: 'Brake Service', labelFr: 'Service freins' },
      { value: 'hvac', label: 'HVAC Service', labelFr: 'Service CVAC' },
      { value: 'electrical', label: 'Electrical', labelFr: 'Électrique' },
      { value: 'other', label: 'Other', labelFr: 'Autre' },
    ],
    section: 'Equipment Info',
    sectionFr: 'Informations équipement',
  },
  {
    name: 'priority',
    label: 'Priority',
    labelFr: 'Priorité',
    type: 'select',
    options: [
      { value: 'low', label: 'Low', labelFr: 'Basse' },
      { value: 'medium', label: 'Medium', labelFr: 'Moyenne' },
      { value: 'high', label: 'High', labelFr: 'Haute' },
      { value: 'critical', label: 'Critical', labelFr: 'Critique' },
    ],
    section: 'Equipment Info',
    sectionFr: 'Informations équipement',
  },
  // Schedule
  {
    name: 'scheduledDate',
    label: 'Scheduled Date',
    labelFr: 'Date planifiée',
    type: 'date',
    section: 'Schedule',
    sectionFr: 'Planification',
  },
  {
    name: 'lastCompletedDate',
    label: 'Last Completed Date',
    labelFr: 'Dernière exécution',
    type: 'date',
    section: 'Schedule',
    sectionFr: 'Planification',
  },
  {
    name: 'frequency',
    label: 'Frequency',
    labelFr: 'Fréquence',
    type: 'select',
    options: [
      { value: 'weekly', label: 'Weekly', labelFr: 'Hebdomadaire' },
      { value: 'biweekly', label: 'Bi-weekly', labelFr: 'Bi-hebdomadaire' },
      { value: 'monthly', label: 'Monthly', labelFr: 'Mensuel' },
      { value: 'quarterly', label: 'Quarterly', labelFr: 'Trimestriel' },
      { value: 'semi_annual', label: 'Semi-annual', labelFr: 'Semestriel' },
      { value: 'annual', label: 'Annual', labelFr: 'Annuel' },
      { value: 'every_x_km', label: 'Every X km', labelFr: 'Tous les X km' },
    ],
    section: 'Schedule',
    sectionFr: 'Planification',
  },
  {
    name: 'frequencyValue',
    label: 'Interval (km)',
    labelFr: 'Intervalle (km)',
    type: 'number',
    placeholder: 'e.g., 10000',
    unit: 'km',
    section: 'Schedule',
    sectionFr: 'Planification',
    conditionalOn: { field: 'frequency', values: ['every_x_km'] },
  },
  // Assignment
  {
    name: 'assignedTechnician',
    label: 'Assigned Technician',
    labelFr: 'Technicien assigné',
    type: 'text',
    placeholder: 'e.g., Mike Johnson',
    placeholderFr: 'ex. Michel Tremblay',
    section: 'Assignment',
    sectionFr: 'Attribution',
  },
  {
    name: 'estimatedCost',
    label: 'Estimated Cost',
    labelFr: 'Coût estimé',
    type: 'number',
    placeholder: 'e.g., 500',
    unit: 'CAD',
    section: 'Assignment',
    sectionFr: 'Attribution',
  },
  // Notes
  {
    name: 'notes',
    label: 'Notes',
    labelFr: 'Notes',
    type: 'textarea',
    placeholder: 'Additional notes...',
    placeholderFr: 'Notes additionnelles...',
    section: 'Additional Notes',
    sectionFr: 'Notes additionnelles',
  },
];

export const routeFields: FormField[] = [
  {
    name: 'routeName',
    label: 'Route Name',
    labelFr: 'Nom de l\'itinéraire',
    type: 'text',
    required: true,
    placeholder: 'e.g., Montreal-Toronto Daily',
    placeholderFr: 'ex. Montréal-Toronto quotidien',
    section: 'Route Information',
    sectionFr: 'Informations itinéraire',
  },
  {
    name: 'startLocation',
    label: 'Start Location',
    labelFr: 'Point de départ',
    type: 'text',
    placeholder: 'e.g., Montreal Warehouse',
    placeholderFr: 'ex. Entrepôt Montréal',
    section: 'Route Information',
    sectionFr: 'Informations itinéraire',
  },
  {
    name: 'endLocation',
    label: 'End Location',
    labelFr: 'Point d\'arrivée',
    type: 'text',
    placeholder: 'e.g., Toronto Distribution Center',
    placeholderFr: 'ex. Centre de distribution Toronto',
    section: 'Route Information',
    sectionFr: 'Informations itinéraire',
  },
  {
    name: 'distance',
    label: 'Distance',
    labelFr: 'Distance',
    type: 'number',
    placeholder: 'e.g., 540',
    unit: 'km',
    section: 'Route Details',
    sectionFr: 'Détails de l\'itinéraire',
  },
  {
    name: 'estimatedDuration',
    label: 'Estimated Duration',
    labelFr: 'Durée estimée',
    type: 'number',
    placeholder: 'e.g., 5.5',
    unit: 'hours',
    section: 'Route Details',
    sectionFr: 'Détails de l\'itinéraire',
  },
  {
    name: 'chargingStops',
    label: 'Charging Stops',
    labelFr: 'Arrêts recharge',
    type: 'number',
    placeholder: 'e.g., 2',
    section: 'Route Details',
    sectionFr: 'Détails de l\'itinéraire',
  },
  {
    name: 'elevationGain',
    label: 'Elevation Gain',
    labelFr: 'Dénivelé positif',
    type: 'number',
    placeholder: 'e.g., 500',
    unit: 'm',
    section: 'Route Details',
    sectionFr: 'Détails de l\'itinéraire',
  },
  {
    name: 'trafficLevel',
    label: 'Traffic Level',
    labelFr: 'Niveau de trafic',
    type: 'select',
    options: [
      { value: 'low', label: 'Low', labelFr: 'Faible' },
      { value: 'medium', label: 'Medium', labelFr: 'Moyen' },
      { value: 'high', label: 'High', labelFr: 'Élevé' },
    ],
    section: 'Conditions',
    sectionFr: 'Conditions',
  },
  {
    name: 'preferredTime',
    label: 'Preferred Departure Time',
    labelFr: 'Heure de départ préférée',
    type: 'time',
    section: 'Conditions',
    sectionFr: 'Conditions',
  },
  {
    name: 'daysOfWeek',
    label: 'Days of Week',
    labelFr: 'Jours de la semaine',
    type: 'multiselect',
    options: [
      { value: 'mon', label: 'Monday', labelFr: 'Lundi' },
      { value: 'tue', label: 'Tuesday', labelFr: 'Mardi' },
      { value: 'wed', label: 'Wednesday', labelFr: 'Mercredi' },
      { value: 'thu', label: 'Thursday', labelFr: 'Jeudi' },
      { value: 'fri', label: 'Friday', labelFr: 'Vendredi' },
      { value: 'sat', label: 'Saturday', labelFr: 'Samedi' },
      { value: 'sun', label: 'Sunday', labelFr: 'Dimanche' },
    ],
    section: 'Conditions',
    sectionFr: 'Conditions',
  },
  {
    name: 'notes',
    label: 'Notes',
    labelFr: 'Notes',
    type: 'textarea',
    placeholder: 'Additional notes...',
    placeholderFr: 'Notes additionnelles...',
    section: 'Additional Notes',
    sectionFr: 'Notes additionnelles',
  },
];

export const chargingFields: FormField[] = [
  {
    name: 'stationName',
    label: 'Station Name',
    labelFr: 'Nom de la station',
    type: 'text',
    required: true,
    placeholder: 'e.g., HQ Depot Charger 1',
    placeholderFr: 'ex. Borne dépôt siège 1',
    section: 'Station Information',
    sectionFr: 'Informations station',
  },
  {
    name: 'address',
    label: 'Address',
    labelFr: 'Adresse',
    type: 'text',
    placeholder: 'e.g., 123 Industrial Blvd',
    placeholderFr: 'ex. 123 boul. Industriel',
    section: 'Station Information',
    sectionFr: 'Informations station',
  },
  {
    name: 'latitude',
    label: 'Latitude',
    labelFr: 'Latitude',
    type: 'number',
    placeholder: 'e.g., 45.5017',
    section: 'Location',
    sectionFr: 'Localisation',
  },
  {
    name: 'longitude',
    label: 'Longitude',
    labelFr: 'Longitude',
    type: 'number',
    placeholder: 'e.g., -73.5673',
    section: 'Location',
    sectionFr: 'Localisation',
  },
  {
    name: 'chargerType',
    label: 'Charger Type',
    labelFr: 'Type de borne',
    type: 'select',
    options: [
      { value: 'level2', label: 'Level 2 AC', labelFr: 'Niveau 2 AC' },
      { value: 'dcfc', label: 'DC Fast Charger', labelFr: 'Borne rapide DC' },
      { value: 'ultra_fast', label: 'Ultra Fast (350kW+)', labelFr: 'Ultra rapide (350kW+)' },
      { value: 'h2_station', label: 'Hydrogen Station', labelFr: 'Station hydrogène' },
    ],
    section: 'Technical Specs',
    sectionFr: 'Spécifications techniques',
  },
  {
    name: 'powerOutput',
    label: 'Power Output',
    labelFr: 'Puissance',
    type: 'number',
    placeholder: 'e.g., 150',
    unit: 'kW',
    section: 'Technical Specs',
    sectionFr: 'Spécifications techniques',
  },
  {
    name: 'numberOfPorts',
    label: 'Number of Ports',
    labelFr: 'Nombre de ports',
    type: 'number',
    placeholder: 'e.g., 2',
    section: 'Technical Specs',
    sectionFr: 'Spécifications techniques',
  },
  {
    name: 'costPerUnit',
    label: 'Cost per kWh or kg',
    labelFr: 'Coût par kWh ou kg',
    type: 'number',
    placeholder: 'e.g., 0.35',
    unit: 'CAD',
    section: 'Pricing',
    sectionFr: 'Tarification',
  },
  {
    name: 'network',
    label: 'Network',
    labelFr: 'Réseau',
    type: 'text',
    placeholder: 'e.g., ChargePoint, FLO, HTEC',
    section: 'Access',
    sectionFr: 'Accès',
  },
  {
    name: 'access',
    label: 'Access Type',
    labelFr: 'Type d\'accès',
    type: 'select',
    options: [
      { value: 'public', label: 'Public', labelFr: 'Public' },
      { value: 'private', label: 'Private', labelFr: 'Privé' },
      { value: 'network_member', label: 'Network Member', labelFr: 'Membre du réseau' },
    ],
    section: 'Access',
    sectionFr: 'Accès',
  },
  {
    name: 'operatingHours',
    label: 'Operating Hours',
    labelFr: 'Heures d\'ouverture',
    type: 'text',
    placeholder: 'e.g., 24/7 or 6am-10pm',
    placeholderFr: 'ex. 24/7 ou 6h-22h',
    section: 'Access',
    sectionFr: 'Accès',
  },
  {
    name: 'status',
    label: 'Status',
    labelFr: 'Statut',
    type: 'select',
    options: [
      { value: 'operational', label: 'Operational', labelFr: 'Opérationnel' },
      { value: 'out_of_service', label: 'Out of Service', labelFr: 'Hors service' },
      { value: 'coming_soon', label: 'Coming Soon', labelFr: 'Bientôt disponible' },
    ],
    section: 'Access',
    sectionFr: 'Accès',
  },
  {
    name: 'notes',
    label: 'Notes',
    labelFr: 'Notes',
    type: 'textarea',
    placeholder: 'Additional notes...',
    placeholderFr: 'Notes additionnelles...',
    section: 'Additional Notes',
    sectionFr: 'Notes additionnelles',
  },
];

export const metricsFields: FormField[] = [
  {
    name: 'metricName',
    label: 'Metric Name',
    labelFr: 'Nom de la métrique',
    type: 'text',
    required: true,
    placeholder: 'e.g., Average Energy Consumption',
    placeholderFr: 'ex. Consommation énergétique moyenne',
    section: 'Metric Information',
    sectionFr: 'Informations métrique',
  },
  {
    name: 'value',
    label: 'Value',
    labelFr: 'Valeur',
    type: 'number',
    required: true,
    placeholder: 'e.g., 1.8',
    section: 'Metric Information',
    sectionFr: 'Informations métrique',
  },
  {
    name: 'unit',
    label: 'Unit',
    labelFr: 'Unité',
    type: 'text',
    placeholder: 'e.g., kWh/km',
    section: 'Metric Information',
    sectionFr: 'Informations métrique',
  },
  {
    name: 'dateRecorded',
    label: 'Date Recorded',
    labelFr: 'Date d\'enregistrement',
    type: 'date',
    section: 'Metric Information',
    sectionFr: 'Informations métrique',
  },
  {
    name: 'category',
    label: 'Category',
    labelFr: 'Catégorie',
    type: 'text',
    placeholder: 'e.g., Energy, Performance, Cost',
    placeholderFr: 'ex. Énergie, Performance, Coût',
    section: 'Metric Information',
    sectionFr: 'Informations métrique',
  },
  {
    name: 'notes',
    label: 'Notes',
    labelFr: 'Notes',
    type: 'textarea',
    placeholder: 'Additional notes...',
    placeholderFr: 'Notes additionnelles...',
    section: 'Additional Notes',
    sectionFr: 'Notes additionnelles',
  },
];

export function getFieldsForCategory(category: string): FormField[] {
  switch (category) {
    case 'drivers': return driverFields;
    case 'vehicles': return vehicleFields;
    case 'maintenance': return maintenanceFields;
    case 'routes': return routeFields;
    case 'charging': return chargingFields;
    case 'metrics': return metricsFields;
    case 'other': return [];
    default: return [];
  }
}
