import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { pdf } from '@react-pdf/renderer';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { AnalyticsReportPDF, AnalyticsKPIs, AnalyticsPDFTranslations } from './AnalyticsReportPDF';

interface AnalyticsPDFDownloadButtonProps {
  kpis: AnalyticsKPIs;
  mode: 'portfolio' | 'project' | 'scenario';
  projectName?: string;
  scenarioName?: string;
  generatedBy?: string;
  variant?: 'default' | 'outline' | 'ghost';
  size?: 'default' | 'sm' | 'lg' | 'icon';
}

export const AnalyticsPDFDownloadButton = ({
  kpis,
  mode,
  projectName,
  scenarioName,
  generatedBy,
  variant = 'outline',
  size = 'default',
}: AnalyticsPDFDownloadButtonProps) => {
  const { t, i18n } = useTranslation();
  const [isGenerating, setIsGenerating] = useState(false);

  // Build translations object for PDF
  const translations: AnalyticsPDFTranslations = {
    platformSubtitle: t('reports.pdf.platformSubtitle', 'Fleet TCO Analysis Platform'),
    reportTitle: t('analytics.pdf.title', 'Analytics Report'),
    portfolioOverview: t('analytics.pdf.portfolioOverview', 'Portfolio Overview'),
    projectOverview: t('analytics.pdf.projectOverview', 'Project Overview'),
    basedOn: t('analytics.pdf.basedOn', 'Based on'),
    scenarios: t('common.scenarios', 'scenarios'),
    projects: t('common.projects', 'projects'),
    financialBreakdown: t('analytics.pdf.financialBreakdown', 'Financial Breakdown'),
    subsidyAnalysis: t('analytics.pdf.subsidyAnalysis', 'Subsidy Analysis'),
    dataSources: t('analytics.pdf.dataSources', 'Data Sources'),
    fleetComposition: t('reports.pdf.fleetComposition', 'Fleet Composition'),
    environmentalImpact: t('analytics.pdf.environmentalImpact', 'Environmental Impact'),
    zevRate: t('analytics.pdf.zevRate', 'ZEV Rate'),
    tcoTotal: t('analytics.kpis.tcoTotal', 'TCO Total'),
    tcoSavings: t('analytics.kpis.tcoSavings', 'TCO Savings'),
    co2Reduction: t('reports.pdf.co2Reduction', 'CO₂ Reduction'),
    vehicles: t('reports.pdf.vehicles', 'Vehicles'),
    paybackPeriod: t('reports.pdf.paybackPeriod', 'Payback Period'),
    years: t('reports.pdf.years', 'years'),
    capex: t('analytics.kpis.capex', 'CAPEX'),
    opex: t('analytics.kpis.opex', 'OPEX'),
    npv: t('reports.pdf.npv', 'NPV'),
    tcoPerKm: t('analytics.kpis.tcoPerKm', 'TCO per km'),
    totalSubsidies: t('analytics.subsidies.total', 'Total Subsidies'),
    riskLevel: t('analytics.subsidies.riskLevel', 'Risk Level'),
    tcoDependency: t('analytics.subsidies.tcoDependency', 'TCO Dependency'),
    bev: t('common.bev', 'BEV'),
    fcev: t('common.fcev', 'FCEV'),
    diesel: t('common.diesel', 'Diesel'),
    disclaimer: t('reports.pdf.disclaimer', 'This report is for planning purposes only. Actual results may vary based on market conditions and operational factors.'),
    low: t('common.low', 'Low'),
    medium: t('common.medium', 'Medium'),
    high: t('common.high', 'High'),
    critical: t('common.critical', 'Critical'),
    investmentBreakdown: t('analytics.charts.investmentBreakdown', 'Investment Breakdown'),
    fleetMix: t('analytics.charts.fleetMix', 'Fleet Mix'),
    reportGeneratedBy: t('reports.pdf.generatedBy', 'Generated by'),
    vsBaseline: t('analytics.vsBaseline', 'vs Baseline'),
    tonnes: t('common.tonnes', 'tonnes'),
  };

  const handleDownload = async () => {
    if (kpis.sourceScenarioCount === 0) {
      toast.error(t('analytics.export.noData', 'No data to export'));
      return;
    }

    setIsGenerating(true);
    try {
      const blob = await pdf(
        <AnalyticsReportPDF
          kpis={kpis}
          translations={translations}
          locale={i18n.language === 'fr' ? 'fr-CA' : 'en-CA'}
          mode={mode}
          projectName={projectName}
          scenarioName={scenarioName}
          generatedBy={generatedBy}
        />
      ).toBlob();

      // Create download link
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      
      // Generate filename based on mode
      const dateSuffix = new Date().toISOString().split('T')[0];
      const namePrefix = mode === 'scenario' && scenarioName 
        ? scenarioName.replace(/\s+/g, '-').toLowerCase()
        : mode === 'project' && projectName
        ? projectName.replace(/\s+/g, '-').toLowerCase()
        : 'portfolio';
      
      link.download = `analytics-report-${namePrefix}-${dateSuffix}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success(t('analytics.export.pdfSuccess', 'PDF exported successfully'));
    } catch (error) {
      console.error('PDF generation error:', error);
      toast.error(t('analytics.export.pdfError', 'Error generating PDF'));
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Button
      variant={variant}
      size={size}
      onClick={handleDownload}
      disabled={isGenerating || kpis.sourceScenarioCount === 0}
    >
      {isGenerating ? (
        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
      ) : (
        <FileDown className="h-4 w-4 mr-2" />
      )}
      {t('common.exportPdf', 'Export PDF')}
    </Button>
  );
};

export default AnalyticsPDFDownloadButton;
