import { useState } from 'react';
import { pdf } from '@react-pdf/renderer';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import { ComparisonReportPDF } from './ComparisonReportPDF';
import { useToast } from '@/hooks/use-toast';
import { useTranslation } from 'react-i18next';

interface ScenarioWithResult {
  id: string;
  name: string;
  region: string;
  tco_result?: {
    tco_total: number;
    tco_per_km: number;
    capex: number;
    opex_total: number;
    co2_total: number;
    co2_savings_percent: number;
    npv: number;
    payback_period_years: number | null;
  };
}

interface ComparisonPDFDownloadButtonProps {
  scenarios: ScenarioWithResult[];
  projectName?: string;
}

export function ComparisonPDFDownloadButton({ scenarios, projectName }: ComparisonPDFDownloadButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();
  const { t, i18n } = useTranslation();

  const handleDownload = async () => {
    if (scenarios.length < 2) return;
    
    setIsGenerating(true);
    
    try {
      const locale = i18n.language === 'fr' ? 'fr-CA' : 'en-CA';
      const translations = {
        comparisonTitle: t('comparison.title', 'Scenario Comparison'),
        summaryTable: t('comparison.summaryTable', 'Summary Table'),
        tcoTotal: t('comparison.tcoTotal', 'Total TCO'),
        capex: t('comparison.capex', 'CAPEX'),
        opex: t('comparison.opex', 'OPEX'),
        co2Total: t('comparison.co2Total', 'CO₂ (tonnes)'),
        co2Savings: t('comparison.co2Savings', 'CO₂ Reduction'),
        payback: t('comparison.payback', 'Payback (years)'),
        npv: t('comparison.npv', 'NPV'),
        tcoPerKm: t('comparison.tcoPerKm', 'TCO/km'),
        region: t('common.region', 'Region'),
        scenarioName: t('comparison.scenarioName', 'Scenario'),
        recommendedScenario: t('reports.pdf.recommendedScenario', 'Recommended Scenario'),
        lowestTco: t('reports.pdf.lowestTco', 'Lowest TCO'),
        disclaimer: t('reports.pdf.disclaimer', 'TCO estimates are for planning purposes only.'),
        reportDate: t('reports.pdf.reportDate', 'Report date'),
        generatedBy: t('reports.pdf.reportGeneratedBy', 'Report generated by'),
      };
      
      const blob = await pdf(
        <ComparisonReportPDF 
          scenarios={scenarios}
          projectName={projectName}
          translations={translations}
          locale={locale}
        />
      ).toBlob();
      
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `Comparison-Report-${projectName || 'Scenarios'}-${new Date().toISOString().split('T')[0]}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast({
        title: t('reports.pdf.generated', 'PDF generated'),
        description: t('reports.pdf.downloadSuccess', 'The report was downloaded successfully.'),
      });
    } catch (error) {
      console.error('Error generating comparison PDF:', error);
      toast({
        title: t('common.error', 'Error'),
        description: t('reports.pdf.downloadError', 'Unable to generate the PDF. Please try again.'),
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Button variant="outline" onClick={handleDownload} disabled={isGenerating || scenarios.length < 2}>
      {isGenerating ? (
        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
      ) : (
        <FileDown className="h-4 w-4 mr-2" />
      )}
      {isGenerating ? t('reports.pdf.generating', 'Generating...') : t('comparison.exportPDF', 'Export PDF')}
    </Button>
  );
}

export default ComparisonPDFDownloadButton;
