import { useState } from 'react';
import { pdf } from '@react-pdf/renderer';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import { TCOReportPDF, PDFTranslations } from './TCOReportPDF';
import { TCOResult } from '@/lib/calculations/types';
import { useToast } from '@/hooks/use-toast';
import { useTranslation } from 'react-i18next';

interface Scenario {
  id: string;
  name: string;
  region: string;
  analysis_years?: number;
  analysisYears?: number;
  fleet_composition?: Record<string, { count: number; annualKm?: number }>;
  fleetComposition?: Record<string, { count: number; annualKm?: number }>;
  discount_rate?: number;
  discountRate?: number;
  description?: string;
}

interface PDFDownloadButtonProps {
  scenario: Scenario;
  results: TCOResult;
  generatedBy?: string;
  variant?: 'default' | 'outline' | 'ghost' | 'secondary';
  size?: 'default' | 'sm' | 'lg' | 'icon';
  className?: string;
}

// Helper to get PDF translations from i18n
function getPDFTranslations(t: (key: string, fallback: string) => string): PDFTranslations {
  return {
    platformSubtitle: t('reports.pdf.platformSubtitle', 'Fleet TCO analysis platform'),
    reportTitle: t('reports.pdf.reportTitle', 'TCO Analysis Report'),
    scenario: t('reports.pdf.scenario', 'Scenario'),
    region: t('common.region', 'Region'),
    analysisHorizon: t('scenarios.params.financial.analysisHorizon', 'Analysis horizon'),
    years: t('common.years', 'years'),
    reportDate: t('reports.pdf.reportDate', 'Report date'),
    generatedBy: t('reports.pdf.generatedBy', 'Generated by'),
    tcoTotal: t('reports.pdf.tcoTotal', 'Total TCO'),
    co2Reduction: t('reports.pdf.co2Reduction', 'CO₂ Reduction'),
    vehicles: t('common.vehicles', 'Vehicles'),
    fleetComposition: t('reports.pdf.fleetComposition', 'Fleet Composition'),
    costBreakdown: t('reports.pdf.costBreakdown', 'Cost Breakdown'),
    disclaimer: t('reports.pdf.disclaimer', 'TCO estimates are for planning purposes only. Actual costs may vary based on local conditions. For critical financial decisions, consult an expert.'),
    analysisDetails: t('reports.pdf.analysisDetails', 'Analysis Details'),
    executiveSummary: t('reports.pdf.executiveSummary', 'Executive Summary'),
    costPerKm: t('reports.pdf.costPerKm', 'Cost per kilometer'),
    npv: t('reports.pdf.npv', 'Net Present Value (NPV)'),
    co2ReductionVsDiesel: t('reports.pdf.co2ReductionVsDiesel', 'CO₂ reduction vs 100% diesel'),
    paybackPeriod: t('reports.pdf.paybackPeriod', 'Payback period'),
    totalVehicles: t('reports.pdf.totalVehicles', 'Total vehicles'),
    diesel: t('reports.pdf.diesel', 'Diesel'),
    electricBev: t('reports.pdf.electricBev', 'Electric (BEV)'),
    hydrogenFcev: t('reports.pdf.hydrogenFcev', 'Hydrogen (FCEV)'),
    annualKm: t('reports.pdf.annualKm', 'Annual km'),
    initialCapex: t('reports.pdf.initialCapex', 'Initial CAPEX'),
    totalOpex: t('reports.pdf.totalOpex', 'Total OPEX'),
    residualValue: t('scenarios.params.financial.residualValue', 'Residual value'),
    netTco: t('reports.pdf.netTco', 'Net TCO'),
    chargingInfrastructure: t('reports.pdf.chargingInfrastructure', 'Charging Infrastructure'),
    evChargers: t('scenarios.params.infrastructure.evChargers', 'EV Chargers'),
    evChargersCost: t('reports.pdf.evChargersCost', 'EV chargers cost'),
    h2Stations: t('scenarios.params.infrastructure.h2Stations', 'H₂ Stations'),
    h2StationsCost: t('reports.pdf.h2StationsCost', 'H₂ stations cost'),
    totalInfraCost: t('reports.pdf.totalInfraCost', 'Total infrastructure cost'),
    environmentalImpact: t('reports.pdf.environmentalImpact', 'Environmental Impact'),
    totalCo2Emissions: t('reports.pdf.totalCo2Emissions', 'Total CO₂ emissions'),
    tonnes: t('common.tonnes', 'tonnes'),
    avoidedEmissions: t('reports.pdf.avoidedEmissions', 'Avoided emissions vs 100% diesel'),
    emissionsReduction: t('reports.pdf.emissionsReduction', 'Emissions reduction'),
    assumptionsAndParams: t('reports.pdf.assumptionsAndParams', 'Assumptions and calculation parameters'),
    discountRate: t('scenarios.params.financial.discountRate', 'Discount rate'),
    baselineTco: t('scenarios.comparison.baselineTco', 'Baseline TCO (100% Diesel)'),
    tcoSavingsVsBaseline: t('reports.pdf.tcoSavingsVsBaseline', 'TCO savings vs baseline'),
    reportGeneratedBy: t('reports.pdf.reportGeneratedBy', 'Report generated by'),
    bevConsumption: t('reports.pdf.bevConsumption', 'BEV consumption'),
    h2Consumption: t('reports.pdf.h2Consumption', 'H₂ consumption'),
    dieselConsumption: t('reports.pdf.dieselConsumption', 'Diesel consumption'),
  };
}

export function PDFDownloadButton({
  scenario,
  results,
  generatedBy,
  variant = 'outline',
  size = 'default',
  className
}: PDFDownloadButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();
  const { t, i18n } = useTranslation();

  const handleDownload = async () => {
    setIsGenerating(true);
    
    try {
      const translations = getPDFTranslations(t);
      const locale = i18n.language === 'fr' ? 'fr-CA' : 'en-CA';
      
      const blob = await pdf(
        <TCOReportPDF 
          scenario={scenario} 
          results={results} 
          generatedBy={generatedBy}
          translations={translations}
          locale={locale}
        />
      ).toBlob();
      
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `H2Fleet_TCO-Report_${scenario.name.replace(/\s+/g, '-')}_${new Date().toISOString().split('T')[0]}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      toast({
        title: t('reports.pdf.generated', 'PDF generated'),
        description: t('reports.pdf.downloadSuccess', 'The report was downloaded successfully.'),
      });
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: t('common.error', 'Error'),
        description: t('reports.pdf.downloadError', 'Unable to generate the PDF. Please try again.'),
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Button
      variant={variant}
      size={size}
      onClick={handleDownload}
      disabled={isGenerating}
      className={className}
    >
      {isGenerating ? (
        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
      ) : (
        <FileDown className="h-4 w-4 mr-2" />
      )}
      {isGenerating ? t('reports.pdf.generating', 'Generating...') : t('reports.pdf.exportPdf', 'Export PDF')}
    </Button>
  );
}

export default PDFDownloadButton;
