// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@2.89.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List the H2Fleet fleet-transition projects owned by the signed-in user, most recently updated first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of projects to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").select(
      "id, name, description, country_or_region, currency, default_analysis_horizon_years, default_discount_rate, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Fetch a single H2Fleet project (name, region, currency, analysis horizon, discount rate) by its ID. Only projects the signed-in user can see under RLS are returned.",
  inputSchema: {
    project_id: z2.string().uuid().describe("The project's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").select("*").eq("id", project_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Project not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-scenarios.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_scenarios_default = defineTool3({
  name: "list_scenarios",
  title: "List scenarios in a project",
  description: "List the fleet-transition scenarios (BEV, FCEV, diesel, mixed\u2026) that belong to a given H2Fleet project. Returns scenario id, name, region, analysis horizon, discount rate, and fleet composition.",
  inputSchema: {
    project_id: z3.string().uuid().describe("The parent project's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("scenarios").select("*").eq("project_id", project_id).order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scenarios: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-tco-results.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_tco_results_default = defineTool4({
  name: "get_tco_results",
  title: "Get TCO results for a scenario",
  description: "Return the latest computed Total Cost of Ownership (TCO) results for a given scenario: capex, opex breakdown, cumulative costs, and CO2 emissions.",
  inputSchema: {
    scenario_id: z4.string().uuid().describe("The scenario's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ scenario_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tco_results").select("*").eq("scenario_id", scenario_id).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No TCO results yet for this scenario." }]
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tco_result: data }
    };
  }
});

// src/lib/mcp/tools/create-project.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z5 } from "npm:zod@^3.25.76";
var create_project_default = defineTool5({
  name: "create_project",
  title: "Create a new project",
  description: "Create a new fleet-transition project owned by the signed-in user. Use this when the user wants to start a new H2Fleet analysis (e.g. a new deployment region or a new client mandate).",
  inputSchema: {
    name: z5.string().trim().min(1).describe("Human-readable project name."),
    description: z5.string().trim().optional().describe("Short project description."),
    country_or_region: z5.string().trim().min(1).describe("Country or region code, e.g. 'CA-QC', 'FR', 'US-CA'."),
    currency: z5.string().trim().min(3).max(3).describe("ISO currency code, e.g. 'CAD', 'EUR', 'USD'."),
    default_analysis_horizon_years: z5.number().int().min(1).max(30).describe("Default TCO horizon in years (1-30)."),
    default_discount_rate: z5.number().min(0).max(1).describe("Default discount rate as a decimal, e.g. 0.05 for 5%.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      description: input.description ?? null,
      country_or_region: input.country_or_region,
      currency: input.currency,
      default_analysis_horizon_years: input.default_analysis_horizon_years,
      default_discount_rate: input.default_discount_rate
    }).select("*").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Project created: ${data.id}` }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fihklznbfufhowopwwuc";
var mcp_default = defineMcp({
  name: "h2fleet-mcp",
  title: "H2Fleet MCP",
  version: "0.1.0",
  instructions: "Tools for H2Fleet \u2014 a fleet-electrification planning platform for heavy vehicles (BEV, FCEV hydrogen, biomethane). Use these tools to list the signed-in user's projects, inspect scenarios, read TCO/CO2 results, and create new projects. All calls run as the authenticated user under row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    list_scenarios_default,
    get_tco_results_default,
    create_project_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
