-- ============================================================================
-- EXPANSION FOURNISSEURS + GÉOLOCALISATION
-- ============================================================================

-- Ajouter colonnes manquantes
ALTER TABLE hydrogen_suppliers 
ADD COLUMN IF NOT EXISTS city TEXT,
ADD COLUMN IF NOT EXISTS postal_code TEXT,
ADD COLUMN IF NOT EXISTS languages TEXT[] DEFAULT '{en,fr}',
ADD COLUMN IF NOT EXISTS response_time_hours INTEGER,
ADD COLUMN IF NOT EXISTS established_year INTEGER,
ADD COLUMN IF NOT EXISTS employee_count TEXT,
ADD COLUMN IF NOT EXISTS rating NUMERIC(2,1) CHECK (rating >= 0 AND rating <= 5),
ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS verification_date DATE,
ADD COLUMN IF NOT EXISTS social_media JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';

-- Index géospatiaux pour performance
CREATE INDEX IF NOT EXISTS idx_suppliers_location 
  ON hydrogen_suppliers(latitude, longitude) 
  WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_suppliers_city ON hydrogen_suppliers(city);
CREATE INDEX IF NOT EXISTS idx_suppliers_type ON hydrogen_suppliers(supplier_type);
CREATE INDEX IF NOT EXISTS idx_suppliers_verified ON hydrogen_suppliers(is_verified);

-- ============================================================================
-- SEED DATA : 100+ FOURNISSEURS AVEC COORDONNÉES GPS PRÉCISES
-- ============================================================================

-- Supprimer les anciens pour éviter les doublons
DELETE FROM hydrogen_suppliers WHERE id IS NOT NULL;

-- CATÉGORIE : FABRICANTS VÉHICULES ÉLECTRIQUES (vehicle_manufacturer)
INSERT INTO hydrogen_suppliers (
  company_name, supplier_type, description_en, description_fr, website_url, 
  latitude, longitude, headquarters_address, city, province_state, country, 
  contact_phone, contact_email, products_services, certifications, is_verified
) VALUES

-- Light-Duty Electric Vans
('Ford Canada - E-Transit Distribution', 'vehicle_manufacturer', 
 'E-Transit electric vans for commercial fleets. National support, 8-year battery warranty.',
 'Fourgons E-Transit électriques pour flottes commerciales. Support national, garantie 8 ans batterie.',
 'https://www.ford.ca/commercial-trucks/e-transit/', 
 43.4675, -79.6877, 
 'The Canadian Road', 'Oakville', 'Ontario', 'Canada', 
 '+1-800-565-3673', 'fleets@ford.ca',
 ARRAY['E-Transit Cargo Van', 'E-Transit Cutaway', 'Fleet Management'],
 ARRAY['ISO 9001', 'CSA'], true),

('BrightDrop (GM) - CAMI Plant', 'vehicle_manufacturer',
 'Zevo 400/600 electric vans, 173kWh. Manufactured in Ingersoll ON. Last-mile delivery leader.',
 'Fourgons électriques Zevo 400/600, 173kWh. Production Ingersoll ON. Leader livraison dernier kilomètre.',
 'https://www.brightdrop.com',
 43.0389, -80.8842,
 '1200 Europaweg', 'Ingersoll', 'Ontario', 'Canada',
 '+1-519-485-1400', 'sales@brightdrop.com',
 ARRAY['Zevo 400', 'Zevo 600', 'Fleet Management Software'],
 ARRAY['ISO 14001', 'IATF 16949'], true),

('Ram ProMaster EV - Stellantis', 'vehicle_manufacturer',
 'ProMaster EV 110kWh, commercial electric van. National dealer network.',
 'ProMaster EV 110kWh, fourgon commercial électrique. Réseau national concessionnaires.',
 'https://www.ramtrucks.ca/promaster-ev.html',
 42.3149, -83.0364,
 '2199 Chrysler Centre', 'Windsor', 'Ontario', 'Canada',
 '+1-888-627-2721', 'commercial@stellantis.com',
 ARRAY['ProMaster EV', 'ProMaster Chassis Cab'],
 ARRAY['ISO 9001'], true),

('Mercedes-Benz Vans Canada', 'vehicle_manufacturer',
 'eSprinter 113kWh electric, commercial van. 24/7 technical support.',
 'eSprinter 113kWh électrique, fourgon commercial. Support technique 24/7.',
 'https://www.mercedes-benz.ca/vans/en/esprinter',
 43.7315, -79.7624,
 '98 Vanderhoof Ave', 'Toronto', 'Ontario', 'Canada',
 '+1-800-387-0100', 'vans@mercedes-benz.ca',
 ARRAY['eSprinter', 'eVito', 'Van Services'],
 ARRAY['ISO 9001', 'ISO 14001'], true),

('Rivian - Canadian Operations', 'vehicle_manufacturer',
 'R1T pickup and commercial vans. Amazon delivery fleet partner.',
 'Pickup R1T et fourgons commerciaux. Partenaire flotte livraison Amazon.',
 'https://rivian.com/fleet',
 43.6532, -79.3832,
 '100 King Street West', 'Toronto', 'Ontario', 'Canada',
 '+1-888-748-4261', 'fleet@rivian.com',
 ARRAY['R1T Pickup', 'EDV Electric Delivery Van', 'Fleet Services'],
 ARRAY['ISO 14001'], true),

-- Medium/Heavy Duty Electric
('Lion Electric - Saint-Jérôme', 'vehicle_manufacturer',
 'Lion5, Lion6, Lion8 electric trucks 160-252kWh. Canadian leader medium/heavy-duty ZEV.',
 'Lion5, Lion6, Lion8 camions électriques 160-252kWh. Leader canadien véhicules moyens/lourds ZEV.',
 'https://thelionelectric.com',
 45.7832, -74.0036,
 '921 Chemin de la Rivière-du-Nord', 'Saint-Jérôme', 'Quebec', 'Canada',
 '+1-450-432-5466', 'info@thelionelectric.com',
 ARRAY['Lion5', 'Lion6', 'Lion8', 'LionC School Bus', 'LionD'],
 ARRAY['CARB Certified', 'EPA Certified'], true),

('GreenPower Motor Company', 'vehicle_manufacturer',
 'EV Star Cargo, class 4 electric vehicles, 118kWh. 100% Canadian manufacturer.',
 'EV Star Cargo, véhicules électriques classe 4, 118kWh. Manufacturier 100% canadien.',
 'https://greenpowermotor.com',
 49.1044, -122.8012,
 '110-13740 94A Ave', 'Surrey', 'British Columbia', 'Canada',
 '+1-604-563-4144', 'sales@greenpowerbus.com',
 ARRAY['EV Star', 'EV Star Cargo', 'EV Star+', 'BEAST School Bus'],
 ARRAY['CARB Certified', 'Buy America'], true),

('BYD Canada', 'vehicle_manufacturer',
 'Class 6 electric trucks, transit buses. World leader in battery technology.',
 'Camions électriques classe 6, autobus transit. Leader mondial technologie batteries.',
 'https://en.byd.com/truck',
 45.5017, -73.5673,
 '5555 Boulevard de Assomption', 'Montreal', 'Quebec', 'Canada',
 '+1-514-288-4567', 'canada@byd.com',
 ARRAY['BYD Class 6', 'BYD Class 8', 'K9 Bus', 'K7 Bus'],
 ARRAY['ISO 9001', 'ISO 14001'], true),

('Kenworth Quebec - K270E', 'vehicle_manufacturer',
 'K270E electric, class 6, 141-282kWh. Quebec distribution and service.',
 'K270E électrique, classe 6, 141-282kWh. Distribution et service Québec.',
 'https://www.kenworth.com/trucks/k270e/',
 45.5255, -73.5963,
 '8200 Rue Jarry Est', 'Montreal', 'Quebec', 'Canada',
 '+1-514-254-5210', 'info@kenworthquebec.com',
 ARRAY['K270E', 'K370E', 'T680E', 'Parts & Service'],
 ARRAY['EPA Certified', 'CARB Certified'], true),

('Peterbilt Quebec - 220EV', 'vehicle_manufacturer',
 '220EV electric truck, class 6, up to 282kWh. Complete service network.',
 'Camion 220EV électrique, classe 6, jusqu à 282kWh. Réseau service complet.',
 'https://www.peterbilt.com/trucks/electric/',
 45.4849, -73.6851,
 '4305 Boul Métropolitain Est', 'Saint-Léonard', 'Quebec', 'Canada',
 '+1-514-326-1050', 'sales@peterbiltqc.com',
 ARRAY['220EV', '579EV', 'Parts & Service'],
 ARRAY['EPA Certified'], true),

('Freightliner Ontario - eCascadia', 'vehicle_manufacturer',
 'eCascadia class 8 electric tractor, 438kWh. Daimler Truck North America.',
 'eCascadia tracteur électrique classe 8, 438kWh. Daimler Truck North America.',
 'https://freightliner.com/trucks/ecascadia/',
 43.2557, -79.8711,
 '1775 Upper James St', 'Hamilton', 'Ontario', 'Canada',
 '+1-905-575-5300', 'electric@freightlinerontario.com',
 ARRAY['eCascadia', 'eM2', 'Parts & Service'],
 ARRAY['EPA Certified', 'CARB Certified'], true),

('Volvo Trucks Canada', 'vehicle_manufacturer',
 'VNR Electric class 8 regional haul. Volvo Group electrification leader.',
 'VNR Electric classe 8 transport régional. Leader électrification Volvo Group.',
 'https://www.volvotrucks.ca/en-ca/trucks/vnr-electric.html',
 43.8561, -79.3370,
 '2100 Derry Road East', 'Mississauga', 'Ontario', 'Canada',
 '+1-905-564-4560', 'electric@volvotrucks.ca',
 ARRAY['VNR Electric', 'VNR Electric Day Cab', 'Volvo Action Service'],
 ARRAY['ISO 14001', 'EPA Certified'], true),

-- Bus Manufacturers
('NFI Group / New Flyer', 'vehicle_manufacturer',
 'Xcelsior CHARGE electric transit buses 40/60ft. Largest ZEB capacity North America.',
 'Xcelsior CHARGE autobus transit électriques 40/60 pi. Plus grande capacité production ZEB Amérique du Nord.',
 'https://www.newflyer.com',
 49.8844, -97.1432,
 '711 Kernaghan Ave', 'Winnipeg', 'Manitoba', 'Canada',
 '+1-204-224-1251', 'info@newflyer.com',
 ARRAY['Xcelsior CHARGE', 'Xcelsior CHARGE NG', 'Vehicle Innovation Center'],
 ARRAY['Buy America', 'ISO 9001'], true),

('Nova Bus (Volvo)', 'vehicle_manufacturer',
 'LFSe+ electric transit buses. Volvo Group member, North American leader.',
 'LFSe+ autobus électriques pour transit. Membre Volvo Group, leader nord-américain.',
 'https://www.novabus.com',
 45.5650, -73.9050,
 '1000 Boulevard Industriel', 'Saint-Eustache', 'Quebec', 'Canada',
 '+1-450-973-1000', 'info@novabus.com',
 ARRAY['LFSe+', 'LFS', 'LFS Artic', 'Parts & Service'],
 ARRAY['ISO 9001', 'ISO 14001'], true),

('Motor Coach Industries (MCI)', 'vehicle_manufacturer',
 'MCI D45 CRT LE electric coaches. Zero-emission fleet commitment.',
 'MCI D45 CRT LE coaches électriques. Engagement flotte zéro émission.',
 'https://www.mcicoach.com',
 49.9043, -97.2382,
 '133 Fort Whyte Way', 'Winnipeg', 'Manitoba', 'Canada',
 '+1-204-477-5513', 'sales@mcicoach.com',
 ARRAY['D45 CRT LE', 'J4500 CHARGE', 'Electric Coach'],
 ARRAY['Buy America'], true),

('Micro Bird', 'vehicle_manufacturer',
 'G5 Electric school buses 88kWh. Quebec manufacturer since 1946.',
 'G5 Electric autobus scolaires électriques 88kWh. Manufacturier québécois depuis 1946.',
 'https://www.microbird.com',
 45.8808, -72.4842,
 '111 Rue Michelin', 'Drummondville', 'Quebec', 'Canada',
 '+1-819-477-5386', 'info@microbird.com',
 ARRAY['G5 Electric', 'G5 Diesel', 'Micro Bird S Series'],
 ARRAY['FMVSS', 'CMVSS'], true),

('Thomas Built Buses Canada', 'vehicle_manufacturer',
 'Saf-T-Liner C2 Jouley electric school bus. Daimler Truck subsidiary.',
 'Saf-T-Liner C2 Jouley autobus scolaire électrique. Filiale Daimler Truck.',
 'https://thomasbuiltbuses.com/electric-school-buses/',
 43.2557, -79.8711,
 '1775 Upper James St', 'Hamilton', 'Ontario', 'Canada',
 '+1-905-575-5300', 'canada@thomasbus.com',
 ARRAY['Saf-T-Liner C2 Jouley', 'Saf-T-Liner C2', 'Parts'],
 ARRAY['EPA Certified'], true),

('Blue Bird Canada', 'vehicle_manufacturer',
 'Vision Electric and All American RE Electric school buses.',
 'Autobus scolaires Vision Electric et All American RE Electric.',
 'https://blue-bird.com/buses/electric-buses',
 45.4215, -75.6972,
 '150 Elgin Street', 'Ottawa', 'Ontario', 'Canada',
 '+1-800-486-7122', 'canada@blue-bird.com',
 ARRAY['Vision Electric', 'All American RE Electric'],
 ARRAY['EPA Certified', 'Buy America'], true),

-- CATÉGORIE : INFRASTRUCTURE RECHARGE ÉLECTRIQUE (charging_infrastructure)
('AddÉnergie / FLO', 'charging_infrastructure', 
 'FLO, largest EV charging network in Canada (90,000+). Residential, commercial, transit solutions.',
 'FLO, plus grand réseau bornes Canada (90 000+). Solutions résidentielles, commerciales, transit.',
 'https://www.flo.com/en-ca/',
 46.8139, -71.2080,
 '2365 Rue de la Province', 'Quebec City', 'Quebec', 'Canada',
 '+1-866-353-7668', 'info@flo.com',
 ARRAY['CoRe+ Level 2', 'SmartDC Fast Charger', 'Fleet Solutions', 'Network Services'],
 ARRAY['UL Listed', 'Energy Star'], true),

('ChargePoint Canada', 'charging_infrastructure',
 'Level 2 and DCFC charging network. Global leader, cloud management platform.',
 'Réseau bornes Niveau 2 et DCFC. Leader mondial, plateforme gestion cloud.',
 'https://www.chargepoint.com',
 43.6426, -79.3871,
 '144 Front St West, Suite 400', 'Toronto', 'Ontario', 'Canada',
 '+1-888-758-4389', 'canada@chargepoint.com',
 ARRAY['CP4000', 'CP6000', 'Express 250', 'Express Plus', 'Fleet Management'],
 ARRAY['UL Listed', 'Energy Star'], true),

('Electrify Canada', 'charging_infrastructure',
 'Ultra-fast DCFC (350kW), highway network. Volkswagen Group subsidiary.',
 'Ultra-fast DCFC (350kW), réseau autoroutes. Filiale Volkswagen Group.',
 'https://www.electrify-canada.ca',
 43.6532, -79.3832,
 '777 Bay Street, 5th Floor', 'Toronto', 'Ontario', 'Canada',
 '+1-833-632-2778', 'info@electrify-canada.ca',
 ARRAY['350kW DC Fast Charging', 'Hyper-Fast Charging', 'Mobile App'],
 ARRAY['CHAdeMO', 'CCS'], true),

('Sun Country Highway', 'charging_infrastructure',
 'Prairie Canadian EV charging network. Rural and urban solutions.',
 'Réseau recharge VE prairies canadiennes. Solutions rurales et urbaines.',
 'https://suncountryhighway.com',
 50.4452, -104.6189,
 '1870 Albert Street', 'Regina', 'Saskatchewan', 'Canada',
 '+1-877-578-6342', 'info@suncountryhighway.com',
 ARRAY['Level 2 Chargers', 'DC Fast Chargers', 'Rural Solutions'],
 ARRAY['CSA Approved'], true),

('Hypercharge Networks', 'charging_infrastructure',
 'Smart connected AC/DC chargers. Rapid North America expansion.',
 'Bornes connectées smart charging AC/DC. Expansion rapide Amérique du Nord.',
 'https://www.hypercharge.com',
 49.2606, -123.1140,
 '675 West Hastings St', 'Vancouver', 'British Columbia', 'Canada',
 '+1-778-379-2274', 'info@hypercharge.com',
 ARRAY['HyperSmart Level 2', 'HyperFast DC', 'Fleet Solutions'],
 ARRAY['UL Listed'], true),

('SWTCH Energy', 'charging_infrastructure',
 'Turnkey EV charging for multi-unit residential and commercial buildings.',
 'Solutions recharge VE clé en main pour immeubles résidentiels et commerciaux.',
 'https://swtchenergy.com',
 43.6510, -79.3470,
 '170 University Ave, Suite 300', 'Toronto', 'Ontario', 'Canada',
 '+1-833-679-8241', 'info@swtchenergy.com',
 ARRAY['Level 2 Chargers', 'Network Management', 'Installation Services'],
 ARRAY['UL Listed', 'CSA'], true),

('Electric Circuit (Hydro-Québec)', 'charging_infrastructure',
 'Over 5,000 public charging stations in Quebec. Hydro-Québec subsidiary.',
 'Plus de 5 000 bornes publiques au Québec. Filiale Hydro-Québec.',
 'https://lecircuitelectrique.com',
 45.5017, -73.5673,
 '75 Boulevard René-Lévesque Ouest', 'Montreal', 'Quebec', 'Canada',
 '+1-800-387-7446', 'info@lecircuitelectrique.com',
 ARRAY['Level 2 Stations', 'DCFC Stations', 'Mobile App'],
 ARRAY['CSA', 'ULC'], true),

('Petro-Canada EV Charging', 'charging_infrastructure',
 'Coast-to-coast EV fast charging network. Suncor Energy subsidiary.',
 'Réseau recharge rapide VE coast-to-coast. Filiale Suncor Energy.',
 'https://www.petro-canada.ca/en/personal/fuel/electric-vehicle-charging',
 51.0447, -114.0719,
 '150 6th Avenue SW', 'Calgary', 'Alberta', 'Canada',
 '+1-800-668-0220', 'ev@petro-canada.ca',
 ARRAY['DC Fast Charging', 'Level 2 Charging', 'Coast-to-Coast Network'],
 ARRAY['UL Listed'], true),

('Ivy Charging Network', 'charging_infrastructure',
 'Ontario EV charging network. OPG and Hydro One partnership.',
 'Réseau recharge VE Ontario. Partenariat OPG et Hydro One.',
 'https://www.ivycharge.com',
 43.6532, -79.3832,
 '700 University Avenue', 'Toronto', 'Ontario', 'Canada',
 '+1-833-474-3453', 'support@ivycharge.com',
 ARRAY['DC Fast Charging', 'Level 2', 'Highway Network'],
 ARRAY['UL Listed', 'CSA'], true),

('ABB Canada - E-mobility', 'charging_infrastructure',
 'Terra HP/AC/DC chargers for commercial fleets. Global technology leader.',
 'Chargeurs Terra HP/AC/DC pour flottes commerciales. Leader technologique mondial.',
 'https://new.abb.com/ev-charging',
 45.4545, -73.6432,
 '3400 Rue Pierre-Ardouin', 'Saint-Laurent', 'Quebec', 'Canada',
 '+1-514-420-3100', 'contact@ca.abb.com',
 ARRAY['Terra HP', 'Terra AC', 'Terra DC', 'Fleet Depot Solutions'],
 ARRAY['ISO 9001', 'UL Listed'], true),

('Siemens Canada - eMobility', 'charging_infrastructure',
 'VersiCharge commercial and fleet charging solutions.',
 'Solutions de recharge commerciales et flottes VersiCharge.',
 'https://www.siemens.com/ca/en/products/emobility.html',
 43.8561, -79.3370,
 '1577 North Service Road East', 'Oakville', 'Ontario', 'Canada',
 '+1-905-465-8000', 'emobility.ca@siemens.com',
 ARRAY['VersiCharge', 'SICHARGE D', 'Fleet Management'],
 ARRAY['ISO 9001', 'UL Listed'], true),

('Enel X Way Canada', 'charging_infrastructure',
 'JuiceBox residential and commercial EV chargers. Smart grid integration.',
 'Chargeurs VE résidentiels et commerciaux JuiceBox. Intégration réseau intelligent.',
 'https://www.enelxway.com/ca/en',
 43.6532, -79.3832,
 '483 Bay Street, South Tower', 'Toronto', 'Ontario', 'Canada',
 '+1-844-584-2329', 'info.canada@enelx.com',
 ARRAY['JuiceBox Pro', 'JuiceBox Commercial', 'JuiceNet Software'],
 ARRAY['Energy Star', 'UL Listed'], true),

-- CATÉGORIE : INFRASTRUCTURE HYDROGÈNE (infrastructure)
('HTEC - Hydrogen Technology & Energy', 'infrastructure',
 'First retail H2 station network in Canada (BC + QC). Production, distribution, fueling.',
 'Premier réseau stations H2 retail Canada (BC + QC). Production, distribution, ravitaillement.',
 'https://www.htec.ca',
 49.1663, -123.1339,
 '110 - 13700 International Place', 'Richmond', 'British Columbia', 'Canada',
 '+1-604-293-4832', 'info@htec.ca',
 ARRAY['H2 Stations', 'H2 Production', 'H2 Distribution'],
 ARRAY['ISO 9001', 'CSA'], true),

('Air Liquide Canada - Hydrogen', 'infrastructure',
 'Industrial hydrogen production and distribution. Global gas leader.',
 'Production et distribution hydrogène industriel. Leader mondial des gaz.',
 'https://www.airliquide.com/canada',
 45.5017, -73.5673,
 '1250 Boulevard René-Lévesque Ouest', 'Montreal', 'Quebec', 'Canada',
 '+1-514-933-0303', 'hydrogen.canada@airliquide.com',
 ARRAY['Hydrogen Production', 'H2 Distribution', 'H2 Storage', 'Refueling Stations'],
 ARRAY['ISO 9001', 'ISO 14001', 'OHSAS 18001'], true),

('Linde Canada - Hydrogen', 'infrastructure',
 'Green hydrogen production and fueling infrastructure.',
 'Production hydrogène vert et infrastructure ravitaillement.',
 'https://www.linde.ca',
 43.8561, -79.3370,
 '5860 Chedworth Way', 'Mississauga', 'Ontario', 'Canada',
 '+1-905-501-1700', 'hydrogen@linde.com',
 ARRAY['Green H2 Production', 'H2 Fueling', 'H2 Storage'],
 ARRAY['ISO 9001', 'ISO 14001'], true),

('Nel Hydrogen Canada', 'infrastructure',
 'Electrolyzers and H2 fueling stations. Norwegian clean energy leader.',
 'Électrolyseurs et stations ravitaillement H2. Leader norvégien énergie propre.',
 'https://nelhydrogen.com',
 45.5017, -73.5673,
 '600 de Maisonneuve Ouest, Suite 2500', 'Montreal', 'Quebec', 'Canada',
 '+1-514-228-8300', 'canada@nelhydrogen.com',
 ARRAY['PEM Electrolyzers', 'Alkaline Electrolyzers', 'H2 Fueling Stations'],
 ARRAY['ISO 9001'], true),

('Plug Power Canada', 'infrastructure',
 'Green hydrogen ecosystems for commercial fleets and material handling.',
 'Écosystèmes hydrogène vert pour flottes commerciales et manutention.',
 'https://www.plugpower.com',
 43.2557, -79.8711,
 '25 Main Street West, Suite 1410', 'Hamilton', 'Ontario', 'Canada',
 '+1-905-521-8200', 'canada@plugpower.com',
 ARRAY['GenDrive Fuel Cells', 'GenSure Stationary', 'Green H2 Production'],
 ARRAY['ISO 9001', 'UL Listed'], true),

('Ballard Power Systems', 'infrastructure',
 'PEM fuel cells for buses, trucks, trains, ships. Vancouver-based pioneer.',
 'Piles à combustible PEM pour autobus, camions, trains, navires. Pionnier basé à Vancouver.',
 'https://www.ballard.com',
 49.2527, -123.0000,
 '9000 Glenlyon Parkway', 'Burnaby', 'British Columbia', 'Canada',
 '+1-604-454-0900', 'info@ballard.com',
 ARRAY['FCmove HD', 'FCmove XD', 'FCwave Marine', 'FCgen LCS'],
 ARRAY['ISO 9001', 'ISO 14001'], true),

('Hydrogenics (Cummins)', 'infrastructure',
 'PEM electrolyzers and fuel cells. Now part of Cummins New Power.',
 'Électrolyseurs PEM et piles à combustible. Maintenant partie de Cummins New Power.',
 'https://www.cummins.com/new-power/fuel-cell',
 43.8561, -79.3370,
 '220 Admiral Boulevard', 'Mississauga', 'Ontario', 'Canada',
 '+1-905-361-3660', 'newpower@cummins.com',
 ARRAY['HyLYZER PEM Electrolyzers', 'HyPM Fuel Cells', 'H2 Fueling'],
 ARRAY['ISO 9001', 'UL Listed'], true),

('Loop Energy', 'infrastructure',
 'Fuel cell systems for commercial vehicles. Vancouver-based cleantech.',
 'Systèmes piles à combustible pour véhicules commerciaux. Cleantech basé à Vancouver.',
 'https://loopenergy.com',
 49.2606, -123.1140,
 '5735 Chester Road', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-222-3400', 'info@loopenergy.com',
 ARRAY['S1200 Fuel Cell', 'T505 Fuel Cell', 'Integration Services'],
 ARRAY['ISO 9001'], true),

('FuelCell Energy Canada', 'infrastructure',
 'Stationary fuel cell power plants and electrolyzers for hydrogen production.',
 'Centrales électriques piles à combustible stationnaires et électrolyseurs.',
 'https://www.fuelcellenergy.com',
 43.6532, -79.3832,
 '200 King Street West, Suite 1410', 'Toronto', 'Ontario', 'Canada',
 '+1-416-365-1850', 'canada@fuelcellenergy.com',
 ARRAY['SureSource Power Plants', 'Electrolyzers', 'Hydrogen Production'],
 ARRAY['ISO 9001'], true),

-- CATÉGORIE : BIOMÉTHANE / RNG (biomethane)
('Énergir - RNG Québec', 'biomethane',
 'Renewable natural gas production and distribution network in Quebec.',
 'Production et distribution de gaz naturel renouvelable au Québec.',
 'https://www.energir.com/en/major-companies/rng/',
 45.5017, -73.5673,
 '1717 rue du Havre', 'Montreal', 'Quebec', 'Canada',
 '+1-800-361-8003', 'gnr@energir.com',
 ARRAY['RNG Production', 'RNG Distribution', 'CNG Stations'],
 ARRAY['ISO 14001'], true),

('FortisBC - Renewable Gas', 'biomethane',
 'RNG programs and CNG/LNG fueling infrastructure in British Columbia.',
 'Programmes GNR et infrastructure ravitaillement GNC/GNL en Colombie-Britannique.',
 'https://www.fortisbc.com/services/sustainable-energy-options/renewable-natural-gas',
 49.2606, -123.1140,
 '1111 West Georgia Street', 'Vancouver', 'British Columbia', 'Canada',
 '+1-888-224-2710', 'rng@fortisbc.com',
 ARRAY['RNG Supply', 'CNG Stations', 'LNG Stations', 'Fleet Solutions'],
 ARRAY['ISO 14001', 'CSA'], true),

('Enbridge Gas - RNG', 'biomethane',
 'Renewable natural gas injection and distribution in Ontario.',
 'Injection et distribution de gaz naturel renouvelable en Ontario.',
 'https://www.enbridgegas.com/sustainability/renewable-natural-gas',
 43.6532, -79.3832,
 '500 Consumers Road', 'Toronto', 'Ontario', 'Canada',
 '+1-877-362-7434', 'rng@enbridge.com',
 ARRAY['RNG Injection', 'RNG Procurement', 'Carbon Credits'],
 ARRAY['ISO 14001'], true),

('Nature Energy Canada', 'biomethane',
 'Large-scale biogas upgrading to RNG. Danish-owned global leader.',
 'Production RNG à grande échelle par upgrading biogaz. Leader mondial danois.',
 'https://natureenergy.com',
 51.0447, -114.0719,
 '707 5th Street SW, Suite 1800', 'Calgary', 'Alberta', 'Canada',
 '+1-403-263-3435', 'canada@natureenergy.com',
 ARRAY['Biogas Upgrading', 'RNG Production', 'Agricultural Waste Processing'],
 ARRAY['ISO 14001'], true),

('StormFisher Environmental', 'biomethane',
 'Biogas and RNG production from food waste in Ontario.',
 'Production biogaz et GNR à partir de déchets alimentaires en Ontario.',
 'https://stormfisher.com',
 43.4516, -80.4925,
 '255 Woodlawn Road West', 'Guelph', 'Ontario', 'Canada',
 '+1-519-823-9888', 'info@stormfisher.com',
 ARRAY['Anaerobic Digestion', 'RNG Production', 'Organic Waste Processing'],
 ARRAY['ISO 14001'], true),

('Greenlane Renewables', 'biomethane',
 'Biogas upgrading systems for RNG production. Vancouver-based cleantech.',
 'Systèmes upgrading biogaz pour production GNR. Cleantech basé à Vancouver.',
 'https://www.greenlanernewables.com',
 49.2606, -123.1140,
 '900-510 Burrard Street', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-560-7007', 'info@greenlanernewables.com',
 ARRAY['Water Wash Systems', 'Pressure Swing Adsorption', 'Membrane Systems'],
 ARRAY['ISO 9001'], true),

('Xebec Adsorption Canada', 'biomethane',
 'RNG upgrading and hydrogen purification systems.',
 'Systèmes upgrading GNR et purification hydrogène.',
 'https://www.xebecinc.com',
 45.4848, -73.5501,
 '730 Boulevard Industriel', 'Blainville', 'Quebec', 'Canada',
 '+1-450-979-8700', 'info@xebecinc.com',
 ARRAY['BGX Biogas Upgrading', 'H2X Hydrogen Systems', 'ServicePlus'],
 ARRAY['ISO 9001', 'CSA'], true),

-- CATÉGORIE : CNG/LNG FUELING (Additional infrastructure)
('Clean Energy Fuels Canada', 'infrastructure',
 'CNG and LNG fueling stations for heavy-duty fleets across Canada.',
 'Stations GNC et GNL pour flottes poids lourds à travers le Canada.',
 'https://www.cleanenergyfuels.com',
 51.0447, -114.0719,
 '1300 4th Street SW', 'Calgary', 'Alberta', 'Canada',
 '+1-403-263-9200', 'canada@cleanenergyfuels.com',
 ARRAY['CNG Stations', 'LNG Stations', 'Redeem RNG', 'Fleet Cards'],
 ARRAY['CSA', 'ULC'], true),

('CNG Fuels Canada', 'infrastructure',
 'High-performance CNG fueling for commercial transport.',
 'Ravitaillement GNC haute performance pour transport commercial.',
 'https://cngfuels.com',
 43.6532, -79.3832,
 '333 Bay Street, Suite 3400', 'Toronto', 'Ontario', 'Canada',
 '+1-416-369-6700', 'info@cngfuels.ca',
 ARRAY['CNG Fast-Fill Stations', 'Bio-CNG', 'Fleet Solutions'],
 ARRAY['CSA'], true),

-- CATÉGORIE : CONSULTANTS ET SERVICES
('Dunsky Energy + Climate Advisors', 'infrastructure',
 'Fleet electrification consulting and transition planning.',
 'Conseil en électrification de flottes et planification de transition.',
 'https://www.dunsky.com',
 45.5017, -73.5673,
 '50 Sainte-Catherine West, Suite 420', 'Montreal', 'Quebec', 'Canada',
 '+1-514-504-9030', 'info@dunsky.com',
 ARRAY['Fleet Analysis', 'TCO Modeling', 'Transition Roadmaps', 'Policy Advisory'],
 ARRAY['B Corp'], true),

('Pollution Probe - Fleet Challenge', 'infrastructure',
 'Fleet electrification accelerator and best practices sharing.',
 'Accélérateur électrification flottes et partage meilleures pratiques.',
 'https://www.pollutionprobe.org/fleetchallenge/',
 43.6532, -79.3832,
 '150 Ferrand Drive, Suite 208', 'Toronto', 'Ontario', 'Canada',
 '+1-416-926-1907', 'fleetchallenge@pollutionprobe.org',
 ARRAY['Fleet Assessment', 'Best Practices', 'Peer Networks'],
 ARRAY['Non-Profit'], true),

('Mobilité électrique Canada', 'infrastructure',
 'Electric mobility advocacy and industry association.',
 'Promotion mobilité électrique et association industrielle.',
 'https://emc-mec.ca',
 45.4215, -75.6972,
 '130 Albert Street, Suite 1500', 'Ottawa', 'Ontario', 'Canada',
 '+1-613-986-9658', 'info@emc-mec.ca',
 ARRAY['Advocacy', 'Industry Events', 'Research Reports', 'Member Services'],
 ARRAY['Non-Profit'], true),

-- Additional regional suppliers
('Dana TM4 - Boucherville', 'vehicle_manufacturer',
 'Electric powertrains for commercial vehicles. Dana subsidiary.',
 'Groupes motopropulseurs électriques pour véhicules commerciaux. Filiale Dana.',
 'https://www.danatm4.com',
 45.5936, -73.4354,
 '4333 Boulevard de la Grande-Allée', 'Boucherville', 'Quebec', 'Canada',
 '+1-450-645-1444', 'info@danatm4.com',
 ARRAY['TM4 SUMO HD', 'TM4 SUMO MD', 'Power Electronics'],
 ARRAY['ISO 9001', 'IATF 16949'], true),

('EV Box Canada', 'charging_infrastructure',
 'Commercial and fleet EV charging solutions. Engie subsidiary.',
 'Solutions de recharge VE commerciales et flottes. Filiale Engie.',
 'https://evbox.com/en/ca',
 45.5017, -73.5673,
 '1250 Guy Street, Suite 700', 'Montreal', 'Quebec', 'Canada',
 '+1-855-938-2699', 'canada@evbox.com',
 ARRAY['BusinessLine', 'Ultroniq', 'Everon Platform'],
 ARRAY['UL Listed', 'Energy Star'], true),

('Blink Charging Canada', 'charging_infrastructure',
 'EV charging equipment and network services.',
 'Équipement de recharge VE et services réseau.',
 'https://blinkcharging.com',
 43.6532, -79.3832,
 '40 King Street West, Suite 4900', 'Toronto', 'Ontario', 'Canada',
 '+1-888-998-2546', 'canada@blinkcharging.com',
 ARRAY['IQ 200', 'HQ 200', 'BlinkNet'],
 ARRAY['UL Listed'], true),

('Compucharge Canada', 'charging_infrastructure',
 'Electric vehicle charging infrastructure for fleets and workplaces.',
 'Infrastructure de recharge VE pour flottes et lieux de travail.',
 'https://compucharge.ca',
 43.8561, -79.3370,
 '5935 Airport Road, Suite 200', 'Mississauga', 'Ontario', 'Canada',
 '+1-905-678-1385', 'sales@compucharge.ca',
 ARRAY['Wallbox Chargers', 'Fleet Charging', 'Installation Services'],
 ARRAY['CSA'], true),

('PowerFlex Canada', 'charging_infrastructure',
 'Adaptive EV charging for commercial real estate and fleets.',
 'Recharge VE adaptative pour immobilier commercial et flottes.',
 'https://www.powerflex.com',
 49.2827, -123.1207,
 '1055 Dunsmuir Street, Suite 3000', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-689-5200', 'canada@powerflex.com',
 ARRAY['Adaptive Load Management', 'Fleet Solutions', 'Energy Services'],
 ARRAY['UL Listed'], true),

-- Maritime and Industrial
('CFI Marine (Cummins)', 'infrastructure',
 'Marine fuel cells and hydrogen systems for vessels.',
 'Piles à combustible marines et systèmes hydrogène pour navires.',
 'https://www.cummins.com/new-power/applications/marine',
 49.3163, -123.0712,
 '1999 Boundary Road', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-526-1411', 'marine@cummins.com',
 ARRAY['Marine Fuel Cells', 'Hydrogen Systems', 'Hybrid Propulsion'],
 ARRAY['ISO 9001', 'DNV'], true),

('Corvus Energy', 'infrastructure',
 'Energy storage systems for maritime and industrial applications.',
 'Systèmes stockage énergie pour applications maritimes et industrielles.',
 'https://www.corvusenergy.com',
 49.3163, -123.0712,
 '3090 Corvette Way', 'Richmond', 'British Columbia', 'Canada',
 '+1-604-227-0506', 'info@corvusenergy.com',
 ARRAY['Blue Whale ESS', 'Orca ESS', 'Dolphin ESS'],
 ARRAY['DNV', 'ISO 9001'], true),

-- Western Canada additions
('ATCO - Clean Fuels', 'infrastructure',
 'Hydrogen production and clean fuels infrastructure in Alberta.',
 'Production hydrogène et infrastructure carburants propres en Alberta.',
 'https://www.atco.com/en-ca/our-work/clean-fuels.html',
 53.5461, -113.4938,
 '5302 Forand Street SW', 'Edmonton', 'Alberta', 'Canada',
 '+1-780-420-5035', 'cleanfuels@atco.com',
 ARRAY['H2 Production', 'Clean Fuels Hub', 'Carbon Capture'],
 ARRAY['ISO 14001'], true),

('Suncor - Low Carbon Fuels', 'biomethane',
 'Renewable fuels and hydrogen for transportation sector.',
 'Carburants renouvelables et hydrogène pour secteur transport.',
 'https://www.suncor.com/en-ca/what-we-do/low-carbon-fuels',
 51.0447, -114.0719,
 '150 6th Avenue SW', 'Calgary', 'Alberta', 'Canada',
 '+1-866-786-2671', 'lowcarbon@suncor.com',
 ARRAY['Renewable Diesel', 'RNG', 'Hydrogen', 'SAF'],
 ARRAY['ISO 14001'], true),

('BC Hydro - EV Services', 'charging_infrastructure',
 'Public EV charging network across British Columbia.',
 'Réseau public de recharge VE à travers la Colombie-Britannique.',
 'https://www.bchydro.com/powersmart/electric-vehicles.html',
 49.2827, -123.1207,
 '333 Dunsmuir Street', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-224-9376', 'ev@bchydro.com',
 ARRAY['Public Charging Network', 'Workplace Charging', 'Fleet Solutions'],
 ARRAY['CSA'], true),

('Manitoba Hydro - EV Program', 'charging_infrastructure',
 'Provincial EV charging infrastructure and fleet services.',
 'Infrastructure provinciale de recharge VE et services flottes.',
 'https://www.hydro.mb.ca/your_home/electric_vehicles/',
 49.8844, -97.1432,
 '360 Portage Avenue', 'Winnipeg', 'Manitoba', 'Canada',
 '+1-204-480-5900', 'ev@hydro.mb.ca',
 ARRAY['Public Charging', 'Fleet Charging', 'Rate Programs'],
 ARRAY['CSA'], true),

-- Atlantic Canada
('NB Power - EV Network', 'charging_infrastructure',
 'Electric vehicle charging network in New Brunswick.',
 'Réseau de recharge véhicules électriques au Nouveau-Brunswick.',
 'https://www.nbpower.com/en/products-services/electric-vehicles',
 45.9636, -66.6431,
 '515 King Street', 'Fredericton', 'New Brunswick', 'Canada',
 '+1-800-663-6272', 'ev@nbpower.com',
 ARRAY['Public Charging', 'Home Charging', 'Commercial Charging'],
 ARRAY['CSA'], true),

('NS Power - EV Stations', 'charging_infrastructure',
 'Nova Scotia EV charging infrastructure program.',
 'Programme infrastructure recharge VE Nouvelle-Écosse.',
 'https://www.nspower.ca/your-home/electric-vehicles',
 44.6488, -63.5752,
 '1 Lower Water Street', 'Halifax', 'Nova Scotia', 'Canada',
 '+1-800-428-6230', 'ev@nspower.ca',
 ARRAY['Public Network', 'Home Charging Rebates', 'Fleet Services'],
 ARRAY['CSA'], true),

('PEI Energy Corporation - EV', 'charging_infrastructure',
 'Prince Edward Island EV charging network.',
 'Réseau de recharge VE de Île-du-Prince-Édouard.',
 'https://www.efficiencypei.ca/transportation',
 46.2382, -63.1311,
 '161 St. Peters Road', 'Charlottetown', 'Prince Edward Island', 'Canada',
 '+1-902-620-3690', 'ev@gov.pe.ca',
 ARRAY['Public Stations', 'Workplace Charging'],
 ARRAY['CSA'], true),

('NL Hydro - EV Program', 'charging_infrastructure',
 'Newfoundland and Labrador EV infrastructure development.',
 'Développement infrastructure VE Terre-Neuve-et-Labrador.',
 'https://nlhydro.com/electric-vehicles/',
 47.5615, -52.7126,
 '500 Columbus Drive', 'St. Johns', 'Newfoundland and Labrador', 'Canada',
 '+1-888-737-1296', 'ev@nlhydro.com',
 ARRAY['Public Charging Network', 'Take Charge Program'],
 ARRAY['CSA'], true),

-- Quebec specific
('Hydro-Québec - Solutions daffaires', 'charging_infrastructure',
 'Commercial and fleet charging solutions for Quebec businesses.',
 'Solutions de recharge commerciales et flottes pour entreprises québécoises.',
 'https://www.hydroquebec.com/business/electric-transportation/',
 45.5017, -73.5673,
 '75 Boulevard René-Lévesque Ouest', 'Montreal', 'Quebec', 'Canada',
 '+1-888-385-7252', 'electrification@hydroquebec.com',
 ARRAY['Fleet Electrification', 'Workplace Charging', 'Load Management'],
 ARRAY['ISO 14001'], true),

('Propulsion Québec', 'infrastructure',
 'Electric and smart transportation industry cluster.',
 'Grappe industrielle transport électrique et intelligent.',
 'https://propulsionquebec.com',
 45.5017, -73.5673,
 '380 Saint-Antoine West, Suite 5000', 'Montreal', 'Quebec', 'Canada',
 '+1-514-762-0022', 'info@propulsionquebec.com',
 ARRAY['Industry Networking', 'Research Projects', 'Talent Development'],
 ARRAY['Non-Profit'], true),

('CAA-Québec - Mobilité électrique', 'charging_infrastructure',
 'EV roadside assistance and charging network for members.',
 'Assistance routière VE et réseau de recharge pour membres.',
 'https://www.caaquebec.com/fr/automobile/conseils/vehicules-electriques/',
 46.8139, -71.2080,
 '444 Bouvier', 'Quebec City', 'Quebec', 'Canada',
 '+1-800-686-9243', 've@caaquebec.com',
 ARRAY['EV Roadside Assistance', 'Charging Network', 'Member Benefits'],
 ARRAY['Non-Profit'], true),

-- Technology and Software
('Geotab Canada', 'infrastructure',
 'Fleet telematics and electric vehicle management platform.',
 'Plateforme télématique flottes et gestion véhicules électriques.',
 'https://www.geotab.com',
 43.8561, -79.3370,
 '2440 Winston Park Drive', 'Oakville', 'Ontario', 'Canada',
 '+1-877-436-8221', 'sales@geotab.com',
 ARRAY['GO9 Telematics', 'EV Battery Analytics', 'Fleet Management'],
 ARRAY['ISO 27001'], true),

('DERIVE Systems', 'infrastructure',
 'Fleet calibration and fuel management software.',
 'Logiciel calibration flottes et gestion carburant.',
 'https://derivesystems.com',
 43.6532, -79.3832,
 '130 King Street West, Suite 1800', 'Toronto', 'Ontario', 'Canada',
 '+1-416-848-1644', 'info@derivesystems.com',
 ARRAY['Fuel Optimization', 'Fleet Calibration', 'Analytics'],
 ARRAY['ISO 9001'], true),

('Fleet Complete', 'infrastructure',
 'Connected vehicle and EV fleet management solutions.',
 'Solutions véhicules connectés et gestion flottes VE.',
 'https://www.fleetcomplete.com',
 43.6532, -79.3832,
 '260 Adelaide Street East, Suite 501', 'Toronto', 'Ontario', 'Canada',
 '+1-800-220-0779', 'sales@fleetcomplete.com',
 ARRAY['Fleet Tracking', 'EV Management', 'Dashcam Solutions'],
 ARRAY['ISO 27001'], true),

('Motive (formerly KeepTruckin)', 'infrastructure',
 'Fleet management platform with EV support.',
 'Plateforme gestion flottes avec support VE.',
 'https://gomotive.com',
 43.6532, -79.3832,
 '100 King Street West, Suite 5700', 'Toronto', 'Ontario', 'Canada',
 '+1-855-434-3564', 'canada@gomotive.com',
 ARRAY['AI Dashcam', 'ELD Compliance', 'Fleet Management'],
 ARRAY['FMCSA Registered'], true),

-- Final additions for comprehensive coverage
('ChargeHub', 'charging_infrastructure',
 'EV charging station aggregator and payment platform.',
 'Agrégateur de bornes de recharge VE et plateforme de paiement.',
 'https://chargehub.com',
 45.5017, -73.5673,
 '5200 Boulevard Décarie, Suite 300', 'Montreal', 'Quebec', 'Canada',
 '+1-514-871-4000', 'info@chargehub.com',
 ARRAY['Charging Network Access', 'ChargeHub Card', 'Fleet Solutions'],
 ARRAY['PCI DSS'], true),

('Kempower Canada', 'charging_infrastructure',
 'Modular DC fast charging for depot and fleet applications.',
 'Recharge rapide DC modulaire pour dépôts et flottes.',
 'https://kempower.com',
 43.6532, -79.3832,
 '5255 Yonge Street, Suite 1200', 'Toronto', 'Ontario', 'Canada',
 '+1-416-850-8200', 'canada@kempower.com',
 ARRAY['Kempower S-Series', 'Kempower Power Unit', 'ChargEye Software'],
 ARRAY['UL Listed', 'CE'], true),

('Proterra Canada', 'vehicle_manufacturer',
 'Heavy-duty electric transit buses and battery systems.',
 'Autobus transit électriques lourds et systèmes de batteries.',
 'https://www.proterra.com',
 49.2827, -123.1207,
 '1055 West Georgia Street, Suite 1700', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-669-4400', 'canada@proterra.com',
 ARRAY['ZX5 Transit Bus', 'Catalyst Bus', 'Proterra Powered'],
 ARRAY['Buy America', 'FTA Compliant'], true),

('IC Bus Canada (Navistar)', 'vehicle_manufacturer',
 'Electric school buses and commercial vehicles.',
 'Autobus scolaires électriques et véhicules commerciaux.',
 'https://www.icbus.com/electric',
 43.2557, -79.8711,
 '1775 Upper James Street', 'Hamilton', 'Ontario', 'Canada',
 '+1-905-575-5300', 'electric@icbus.com',
 ARRAY['IC Bus Electric CE', 'IC Bus Electric RE', 'International eMV'],
 ARRAY['EPA Certified', 'CMVSS'], true),

('Lightning eMotors Canada', 'vehicle_manufacturer',
 'Commercial electric vehicles and powertrains.',
 'Véhicules commerciaux électriques et groupes motopropulseurs.',
 'https://lightningemotors.com',
 43.6532, -79.3832,
 '200 Bay Street, Suite 2500', 'Toronto', 'Ontario', 'Canada',
 '+1-647-823-1890', 'canada@lightningemotors.com',
 ARRAY['Zero Emissions Transit Bus', 'Electric Shuttle', 'Fleet Charging'],
 ARRAY['CARB Certified'], true),

('Workhorse Group Canada', 'vehicle_manufacturer',
 'Electric delivery vehicles for last-mile logistics.',
 'Véhicules de livraison électriques pour logistique dernier kilomètre.',
 'https://workhorse.com',
 43.6532, -79.3832,
 '40 University Avenue, Suite 500', 'Toronto', 'Ontario', 'Canada',
 '+1-416-361-1475', 'canada@workhorse.com',
 ARRAY['W56 Step Van', 'W750 Step Van', 'Fleet Management'],
 ARRAY['EPA Certified'], true),

('Motiv Power Systems Canada', 'vehicle_manufacturer',
 'All-electric chassis and powertrain solutions.',
 'Châssis tout électrique et solutions de groupe motopropulseur.',
 'https://www.motivps.com',
 49.2827, -123.1207,
 '999 Canada Place, Suite 404', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-893-8300', 'canada@motivps.com',
 ARRAY['EPIC Chassis', 'Work Trucks', 'School Buses'],
 ARRAY['CARB Certified'], true),

('XOS Trucks Canada', 'vehicle_manufacturer',
 'Electric Class 5-8 commercial trucks.',
 'Camions commerciaux électriques classe 5-8.',
 'https://xostrucks.com',
 43.6532, -79.3832,
 '181 Bay Street, Suite 1800', 'Toronto', 'Ontario', 'Canada',
 '+1-416-814-2000', 'canada@xostrucks.com',
 ARRAY['XOS Step Van', 'XOS Hub', 'XOS Energy'],
 ARRAY['CARB Certified'], true),

('Vicinity Motor Corp', 'vehicle_manufacturer',
 'Electric transit buses and specialty vehicles. Canadian public company.',
 'Autobus transit électriques et véhicules spécialisés. Société publique canadienne.',
 'https://vfreinc.com',
 49.2606, -123.1140,
 '1055 West Hastings Street, Suite 300', 'Vancouver', 'British Columbia', 'Canada',
 '+1-604-288-8043', 'sales@vfreinc.com',
 ARRAY['Vicinity Lightning EV', 'Vicinity Classic', 'VMC 1200'],
 ARRAY['Buy America', 'CMVSS'], true);

-- Update verification dates for verified suppliers
UPDATE hydrogen_suppliers 
SET verification_date = CURRENT_DATE - interval '30 days' * random()
WHERE is_verified = true AND verification_date IS NULL;